export default function FAQSection() {
  return (
    <section id="faq" className="py-16 bg-white/50 dark:bg-gray-800/50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold mb-8">Frequently Asked Questions</h2>
        <div className="grid gap-6 md:grid-cols-2">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <h3 className="text-lg font-semibold mb-3">
              How does WikiTimeline work?
            </h3>
            <p className="text-gray-600 dark:text-gray-400">
              WikiTimeline automatically extracts dates and events from
              Wikipedia articles and presents them in an interactive timeline
              format. Simply paste a Wikipedia URL or search for an article to
              get started.
            </p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <h3 className="text-lg font-semibold mb-3">
              Can I compare multiple timelines?
            </h3>
            <p className="text-gray-600 dark:text-gray-400">
              Yes! You can add multiple Wikipedia articles to create a combined
              timeline, perfect for comparing historical events, biographies, or
              any other chronological information.
            </p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <h3 className="text-lg font-semibold mb-3">
              How often are timelines updated?
            </h3>
            <p className="text-gray-600 dark:text-gray-400">
              Free and Limited plan timelines are generated once and cached.
              Unlimited plan members can force-refresh any timeline to reflect
              the latest Wikipedia content.
            </p>
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
            <h3 className="text-lg font-semibold mb-3">
              What happens to timelines I generate?
            </h3>
            <p className="text-gray-600 dark:text-gray-400">
              Timelines generated by Limited and Unlimited plan members become
              part of our public collection, accessible to all users. This helps
              grow our community knowledge base.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
