export const AVAILABLE_FONTS = [
  { value: "default", label: "Default" },
  { value: "abril-droidsans", label: "Abril & Droid Sans" },
  { value: "amatic-andika", label: "Amatic & Andika" },
  { value: "bevan-pontanosans", label: "Bevan & Pontano Sans" },
  { value: "bitter-raleway", label: "Bitter & Raleway" },
  { value: "clicker-garamond", label: "Clicker & Garamond" },
  { value: "dancing-ledger", label: "Dancing & Ledger" },
  { value: "fjalla-average", label: "Fjalla & Average" },
  { value: "georgia-helvetica", label: "Georgia & Helvetica" },
  { value: "lustria-lato", label: "Lustria & Lato" },
  { value: "medula-lato", label: "Medula & Lato" },
  { value: "oldstandard", label: "Old Standard" },
  { value: "opensans-gentiumbook", label: "Open Sans & Gentium Book" },
  { value: "playfair-faunaone", label: "Playfair & Fauna One" },
  { value: "playfair", label: "Playfair" },
  { value: "pt", label: "PT" },
  { value: "roboto-megrim", label: "Roboto & Megrim" },
  { value: "rufina-sintony", label: "Rufina & Sintony" },
  { value: "ubuntu", label: "Ubuntu" },
  { value: "unicaone-vollkorn", label: "Unica One & Vollkorn" },
] as const;
